spring.application.name=medisphere-admin-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-delicate-mountain-a1q5imc7-pooler.ap-southeast-1.aws.neon.tech:5432/admin_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_diF1rxTb0fps
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Server Configuration
server.port=8089

# Optional: Logging to see what's happening
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO


# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/